
import yaml
from snakemake.utils import min_version

min_version("8.10")

configfile: workflow.source_path("../config/config.yaml")

with open(workflow.source_path("internal/settings.yaml"), "r", encoding="utf-8") as f:
    internal = yaml.safe_load(f)

include: "rules/automatic.smk"
include: "rules/prepare.smk"
include: "rules/projections.smk"
include: "rules/transformations.smk"
include: "rules/visualizations.smk"
include: "rules/spatial.smk"

rule all:
    input:
        rules.demand_all.output
