from __future__ import annotations

import argparse
import colorsys
import html
import math
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
import pydeck as pdk
import yaml


def _load_yaml(path: str | Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _load_cfg(visualization_config: str, model_config: str) -> dict:
    vis = _load_yaml(visualization_config).get("visualization", {})
    model = _load_yaml(model_config)
    return {
        "visualization": vis,
        "spatial_disaggregation": model.get("spatial_disaggregation", {}),
    }


def _region_column(df: pd.DataFrame, configured: str | None = None) -> str:
    # Spatial disaggregation may create region_x/region_y after a merge.
    # region_y is the regional key generated by the spatial distribution table.
    candidates = ["region_y", "region", configured, "region_x", "name", "bus", "region_id", "region_name"]
    for col in candidates:
        if col and col in df.columns:
            return col
    raise ValueError(
        "Could not identify region column. Available columns: "
        + ", ".join(df.columns.astype(str))
    )


def _normalise_region_column(df: pd.DataFrame, configured: str | None, label: str) -> pd.DataFrame:
    out = df.copy()
    col = _region_column(out, configured)
    out["region"] = out[col].astype(str)
    print(f"Spatial maps: using '{col}' as region column for {label}.")
    return out


def _prepare_regions(path: str, cfg: dict) -> gpd.GeoDataFrame:
    regions = gpd.read_file(path)
    region_col = cfg.get("spatial_disaggregation", {}).get("region_id_column", "name")
    if region_col not in regions.columns:
        raise ValueError(f"GeoJSON region id column '{region_col}' not found.")
    regions = regions.copy()
    regions["region"] = regions[region_col].astype(str)
    if regions.crs is None:
        regions = regions.set_crs("EPSG:4326")
    return regions.to_crs("EPSG:4326")


def _selected_years(cfg: dict, available_years) -> list[int]:
    spatial_maps = cfg.get("visualization", {}).get("spatial_maps", {})
    years = spatial_maps.get("years")
    if years is None:
        years = cfg.get("spatial_disaggregation", {}).get("years")
    available = sorted({int(y) for y in available_years if pd.notna(y)})
    if years is None:
        return available
    requested = [int(y) for y in years]
    missing = sorted(set(requested) - set(available))
    if missing:
        print(f"Spatial maps: requested years not available: {missing}")
    return [y for y in requested if y in available]


def _view_state(regions: gpd.GeoDataFrame) -> pdk.ViewState:
    minx, miny, maxx, maxy = regions.total_bounds
    lon = (minx + maxx) / 2
    lat = (miny + maxy) / 2
    span = max(maxx - minx, maxy - miny)
    zoom = 4.0 if span > 20 else 5.0 if span > 10 else 6.0
    return pdk.ViewState(longitude=lon, latitude=lat, zoom=zoom, pitch=0)


def _deck(layers, regions) -> pdk.Deck:
    return pdk.Deck(
        layers=layers,
        initial_view_state=_view_state(regions),
        map_provider="carto",
        map_style="light",
        tooltip={
            "html": "{tooltip}",
            "style": {"backgroundColor": "white", "color": "black"},
        },
    )


def _write_html(deck: pdk.Deck, path: Path, title: str, legend_html: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    deck.to_html(path, open_browser=False)
    text = path.read_text(encoding="utf-8")
    title_block = (
        '<div style="position:absolute;left:15px;top:15px;z-index:9999;'
        'background:white;padding:8px 11px;border-radius:4px;'
        'box-shadow:0 1px 5px rgba(0,0,0,.25);font-family:Arial;font-weight:600;">'
        + html.escape(title)
        + "</div>"
    )
    text = text.replace("<body>", "<body>" + title_block + legend_html, 1)
    path.write_text(text, encoding="utf-8")


def _palette(categories: list[str]) -> dict[str, list[int]]:
    colors = {}
    n = max(len(categories), 1)
    for i, category in enumerate(sorted(categories)):
        r, g, b = colorsys.hsv_to_rgb(i / n, 0.62, 0.82)
        colors[category] = [int(255 * r), int(255 * g), int(255 * b), 220]
    return colors


def _legend(colors: dict[str, list[int]], title: str) -> str:
    rows = []
    for category, color in colors.items():
        rows.append(
            '<div style="display:flex;align-items:center;margin:2px 0;">'
            f'<span style="width:11px;height:11px;background:rgb({color[0]},{color[1]},{color[2]});'
            'display:inline-block;margin-right:6px;border:1px solid #888;"></span>'
            f'<span>{html.escape(category)}</span></div>'
        )
    return (
        '<div style="position:absolute;right:15px;top:15px;z-index:9999;background:white;'
        'padding:8px 10px;border-radius:4px;box-shadow:0 1px 5px rgba(0,0,0,.25);'
        'font-family:Arial;font-size:11px;max-height:70vh;overflow:auto;">'
        f'<div style="font-weight:600;margin-bottom:5px;">{html.escape(title)}</div>'
        + "".join(rows)
        + "</div>"
    )


def _region_centres(regions: gpd.GeoDataFrame) -> pd.DataFrame:
    # representative_point stays inside polygons, which is useful for pies.
    projected = regions.to_crs("EPSG:3035")
    pts = gpd.GeoSeries(projected.geometry.representative_point(), crs=projected.crs).to_crs("EPSG:4326")
    return pd.DataFrame({
        "region": regions["region"].values,
        "lon": pts.x.values,
        "lat": pts.y.values,
    })


def _compress_categories(df: pd.DataFrame, category: str, max_slices: int | None) -> pd.DataFrame:
    grouped = df.groupby(["region", category], as_index=False)["demand"].sum()
    if not max_slices or max_slices < 2:
        return grouped
    totals = grouped.groupby(category)["demand"].sum().sort_values(ascending=False)
    keep = set(totals.head(max_slices - 1).index)
    grouped[category] = grouped[category].where(grouped[category].isin(keep), "OTHER")
    return grouped.groupby(["region", category], as_index=False)["demand"].sum()


def _wedge_polygon(lon: float, lat: float, radius_deg: float, start: float, end: float) -> list[list[float]]:
    # Simple map-coordinate pie geometry. This mirrors the logic of matplotlib
    # Wedge: radius is a map distance, and angle is the category share.
    n = max(5, int(math.ceil(24 * (end - start) / (2 * math.pi))))
    angles = np.linspace(start, end, n + 1)
    # Correct longitude a little so the symbol stays approximately circular.
    cos_lat = max(math.cos(math.radians(lat)), 0.25)
    points = [[lon, lat]]
    for a in angles:
        points.append([
            lon + radius_deg * math.cos(a) / cos_lat,
            lat + radius_deg * math.sin(a),
        ])
    points.append([lon, lat])
    return points


def _pie_records(
    grouped: pd.DataFrame,
    category_col: str,
    centres: pd.DataFrame,
    radius_factor: float,
    colors: dict[str, list[int]],
) -> list[dict]:
    totals = grouped.groupby("region")["demand"].sum()
    max_total = float(totals.max()) if len(totals) else 0.0
    if max_total <= 0:
        return []

    centre_lookup = centres.set_index("region")
    records = []

    for region, rg in grouped.groupby("region"):
        if region not in centre_lookup.index:
            continue
        total = float(rg["demand"].sum())
        if total <= 0:
            continue

        # Same idea as the user's working code: radius ~ sqrt(total).
        # Normalising by max_total makes radius_factor independent of units.
        radius = math.sqrt(total / max_total) * radius_factor
        lon = float(centre_lookup.at[region, "lon"])
        lat = float(centre_lookup.at[region, "lat"])

        angle = -math.pi / 2
        for row in rg.itertuples():
            value = float(getattr(row, "demand"))
            if value <= 0:
                continue
            category = str(getattr(row, category_col))
            share = value / total
            next_angle = angle + 2 * math.pi * share
            records.append({
                "region": str(region),
                "category": category,
                "value": value,
                "total": total,
                "share": 100 * share,
                "polygon": _wedge_polygon(lon, lat, radius, angle, next_angle),
                "color": colors[category],
                "tooltip": (
                    f"<b>{html.escape(str(region))}</b><br/>"
                    f"{html.escape(category)}: {value:,.2f}<br/>"
                    f"Share: {100 * share:.1f}%<br/>"
                    f"Total: {total:,.2f}"
                ),
            })
            angle = next_angle

    return records


def _base_region_layer(regions: gpd.GeoDataFrame):
    base = regions.copy()
    base["tooltip"] = "<b>" + base["region"].astype(str) + "</b>"
    return pdk.Layer(
        "GeoJsonLayer",
        base.__geo_interface__,
        pickable=True,
        filled=True,
        stroked=True,
        get_fill_color=[235, 235, 235, 70],
        get_line_color=[90, 90, 90, 160],
        line_width_min_pixels=0.5,
    )


def make_energy_pie_maps(energy: pd.DataFrame, regions: gpd.GeoDataFrame, cfg: dict, outdir: Path) -> None:
    vis = cfg.get("visualization", {}).get("spatial_maps", {})
    plots = vis.get("plots", {})
    energy_layer = vis.get("energy_layer", "FEC")
    use_types = vis.get("use_types", ["final_energy"])
    max_slices = vis.get("max_pie_slices", 10)
    radius_factor = float(vis.get("pie_radius_factor", 0.45))
    if radius_factor <= 0:
        raise ValueError("visualization.spatial_maps.pie_radius_factor must be > 0")

    data = energy.copy()
    data["year"] = pd.to_numeric(data["year"], errors="coerce")
    data["demand"] = pd.to_numeric(data["demand"], errors="coerce").fillna(0.0)
    if energy_layer is not None and "energy_layer" in data.columns:
        data = data[data["energy_layer"].astype(str).eq(str(energy_layer))]
    if use_types and "use_type" in data.columns:
        data = data[data["use_type"].isin(use_types)]

    years = _selected_years(cfg, data["year"].dropna().astype(int).unique())
    centres = _region_centres(regions)

    sector_col = "sector_name" if "sector_name" in data.columns else "sector"
    specs = []
    if plots.get("energy_by_sector_pies", True):
        specs.append((sector_col, "sector"))
    if plots.get("energy_by_commodity_pies", False):
        specs.append(("commodity", "commodity"))
    if plots.get("energy_by_carrier_pies", False):
        specs.append(("carrier", "carrier"))

    for year in years:
        year_data = data[data["year"] == year]
        for category_col, label in specs:
            if category_col not in year_data.columns:
                print(f"Spatial maps: skipping {label}; column '{category_col}' missing.")
                continue
            grouped = _compress_categories(year_data, category_col, max_slices)
            if grouped.empty or grouped["demand"].sum() <= 0:
                continue
            categories = sorted(grouped[category_col].astype(str).unique())
            colors = _palette(categories)
            records = _pie_records(grouped, category_col, centres, radius_factor, colors)
            if not records:
                continue

            print(
                f"Spatial maps: {label} pies for {year}; "
                f"largest pie radius = {radius_factor:g} map degrees."
            )

            pie_layer = pdk.Layer(
                "PolygonLayer",
                records,
                pickable=True,
                filled=True,
                stroked=True,
                get_polygon="polygon",
                get_fill_color="color",
                get_line_color=[255, 255, 255, 230],
                line_width_min_pixels=0.4,
            )
            deck = _deck([_base_region_layer(regions), pie_layer], regions)
            path = outdir / f"energy_demand_by_{label}_{year}.html"
            _write_html(deck, path, f"Energy demand by {label} — {year}", _legend(colors, label.capitalize()))


def _choropleth_color(values: pd.Series) -> list[list[int]]:
    vals = pd.to_numeric(values, errors="coerce").fillna(0.0)
    vmax = float(vals.max()) if len(vals) else 0.0
    if vmax <= 0:
        return [[230, 230, 230, 100] for _ in vals]
    x = np.sqrt(np.clip(vals / vmax, 0, 1))
    return [[int(245 - 120*v), int(240 - 90*v), int(230 - 150*v), 190] for v in x]


def make_production_maps(route_prod: pd.DataFrame, regions: gpd.GeoDataFrame, cfg: dict, outdir: Path) -> None:
    vis = cfg.get("visualization", {}).get("spatial_maps", {})
    commodities = vis.get("production_commodities")

    data = route_prod.copy()
    data["year"] = pd.to_numeric(data["year"], errors="coerce")
    data["route_production"] = pd.to_numeric(data["route_production"], errors="coerce").fillna(0.0)
    if commodities:
        data = data[data["commodity"].isin(commodities)]

    years = _selected_years(cfg, data["year"].dropna().astype(int).unique())

    for year in years:
        year_data = data[data["year"] == year]
        for commodity, group in year_data.groupby("commodity"):
            if group["route_production"].sum() <= 0:
                continue
            total = group.groupby("region", as_index=False)["route_production"].sum()
            breakdown = group.groupby(["region", "production_route"], as_index=False)["route_production"].sum()
            breakdown = breakdown.sort_values(["region", "route_production"], ascending=[True, False])
            breakdown_text = (
                breakdown.groupby("region")
                .apply(lambda x: "<br/>".join(f"{r.production_route}: {r.route_production:,.2f}" for r in x.itertuples()), include_groups=False)
                .rename("route_breakdown")
                .reset_index()
            )
            total = total.merge(breakdown_text, on="region", how="left")
            gdf = regions.merge(total, on="region", how="left")
            gdf["route_production"] = gdf["route_production"].fillna(0.0)
            gdf["route_breakdown"] = gdf["route_breakdown"].fillna("No production")
            gdf["fill_color"] = _choropleth_color(gdf["route_production"])
            gdf["tooltip"] = (
                "<b>" + gdf["region"].astype(str) + "</b><br/>"
                + f"{commodity}: " + gdf["route_production"].map(lambda x: f"{x:,.2f}")
                + "<br/>" + gdf["route_breakdown"]
            )
            layer = pdk.Layer(
                "GeoJsonLayer",
                gdf.__geo_interface__,
                pickable=True,
                filled=True,
                stroked=True,
                get_fill_color="properties.fill_color",
                get_line_color=[80, 80, 80, 180],
                line_width_min_pixels=0.5,
            )
            deck = _deck([layer], regions)
            _write_html(deck, outdir / f"production_{commodity}_{year}.html", f"{commodity} production — {year}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--visualization-config", required=True)
    parser.add_argument("--model-config", required=True)
    parser.add_argument("--regions", required=True)
    parser.add_argument("--route-production", required=True)
    parser.add_argument("--energy-demand", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    cfg = _load_cfg(args.visualization_config, args.model_config)
    vis = cfg.get("visualization", {}).get("spatial_maps", {})
    if not vis.get("enabled", True):
        print("Spatial maps disabled.")
        return

    regions = _prepare_regions(args.regions, cfg)
    configured_region_col = cfg.get("spatial_disaggregation", {}).get("region_id_column")

    route_prod = _normalise_region_column(
        pd.read_csv(args.route_production, low_memory=False),
        configured_region_col,
        "route production",
    )
    energy = _normalise_region_column(
        pd.read_csv(args.energy_demand, low_memory=False),
        configured_region_col,
        "energy demand",
    )

    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    if vis.get("clean_output_dir", True):
        for p in outdir.glob("*.html"):
            p.unlink()

    plots = vis.get("plots", {})
    if plots.get("production_maps", True):
        make_production_maps(route_prod, regions, cfg, outdir)

    if (
        plots.get("energy_by_sector_pies", True)
        or plots.get("energy_by_commodity_pies", False)
        or plots.get("energy_by_carrier_pies", False)
    ):
        make_energy_pie_maps(energy, regions, cfg, outdir)

    (outdir / ".maps_complete").touch()


if __name__ == "__main__":
    main()
