# Internal source registry.
# These URLs reproduce the data sources used by the original workflow.
resources:
  automatic:
    eurostat: "https://tubcloud.tu-berlin.de/s/prkJpL7B9M3cDPb/download/Balances-April2023.zip"
    jrc_idees: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/JRC-IDEES/JRC-IDEES-2021_v1/JRC-IDEES-2021.zip"
    hotmaps: "https://gitlab.com/hotmaps/industrial_sites/industrial_sites_Industrial_Database/-/raw/master/data/Industrial_Database.csv"
    ammonia:
      plants: "https://raw.githubusercontent.com/PyPSA/pypsa-eur/refs/heads/master/data/ammonia_plants.csv"
      usgs: "https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/files/myb1-2022-nitro-ert.xlsx"
    GEM_SPT: "https://tubcloud.tu-berlin.de/s/Aqebo3rrQZWKGsG/download/Global-Steel-Plant-Tracker-April-2024-Standard-Copy-V1.xlsx"
    CHE_industry: "https://raw.githubusercontent.com/PyPSA/pypsa-eur/refs/heads/master/data/ch_industrial_production_per_subsector.csv"
    non_eu:
      cement: "https://raw.githubusercontent.com/PyPSA/pypsa-eur/refs/heads/master/data/cement-plants-noneu.csv"
      refineries:   "https://raw.githubusercontent.com/PyPSA/pypsa-eur/master/data/refineries-noneu.csv"

